### ISSUE TITLE
What if grammar changed?

### ISSUE THREAD

**Issue by xpol** [nirix/atom-editor-settings#11]
The follow case may cause grammar change:

1. an new file saved with a extension, the atom may set new grammar for the editor
2. user set grammar by choose new grammar.

The 1st case can be fixed by:
~~~Coffeescript
    atom.workspace.observeTextEditors (editor) =>
      editor.observeGrammar =>
        @setEditorConfig editor
~~~

but the 2nd case, the new syntax may not have configured. We have to calculate the correct settings.

**Comment by nirix** [comment]
Fixed in `1.0.1`.
