### ISSUE TITLE
Can't handle grammars with whitespace in name

### ISSUE THREAD

**Issue by gevatter** [nirix/atom-editor-settings#15]
When packages declare grammar names with a whitespace in their name, the settings file would not be loaded regardless if with or without whitespace in filename.

For example: https://atom.io/packages/language-haml

when changing the name to `RubyHaml` in the package grammar file `language-haml/grammars/ruby haml.cson` the belonging config file is loaded.

**Comment by nirix** [comment]
All grammar config file names are a lower case hyphenated string. Just tested the package you linked and it appears to be working.

![screen shot 2016-10-07 at 9 48 41 am](https://cloud.githubusercontent.com/assets/61958/19173506/61e46dfa-8c73-11e6-9443-d9c88927103a.png)

_(Maybe this is an old bug that was fixed and just not closed.)_
