### ISSUE TITLE
Project grammar settings only work if global grammar settings file exists

### ISSUE THREAD

**Issue by joshuajabbour** [nirix/atom-editor-settings#2]
When you config project settings such as 

```
'tabLength': 4
'javascript':
  'tabLength': 2
```

It seems the Javascript-specific settings will not take effect unless the `.atom/grammar-config/javascript.cson` file exists. (The file can be empty, but it needs to exist.) This probably shouldn't be the case.

**Comment by nirix** [comment]
Appears to now be fixed in `1.0.0`
