### ISSUE TITLE
When installed and tabs are unconfigured, it still overrides some of atom's settings

### ISSUE THREAD

**Issue by jolsenmultiad** [nirix/atom-editor-settings#23]
When editor-settings is installed and unconfigured (nothing in grammar-config directory, and no .editor-settings files) it interferes with Atom's built in grammar-specific tab settings. Please adjust editor-settings so Atom-configured global and grammar-specific values still work and only override them if specifically configured in an editor-settings configuration file.

I'd like to use Atom's built-in global and grammar-specific tab length settings, but since Atom doesn't support grammar-specific tab types yet, I'd like to use editor-settings to control what grammars use the default tab type (be it auto, soft, or hard) and which ones override the default with a custom tab type (auto, soft, or hard).

Thanks

**Comment by nirix** [comment]
I haven't been able to reproduce this issue with the latest versions of Atom or Editor Settings.

When editing a file with a grammar that has no tab/indentation settings set, Atom's defaults are used.
