### ISSUE TITLE
Hard tabs

### ISSUE THREAD

**Issue by asbjornu** [nirix/atom-editor-settings#27]
Is it possible to configure a grammar to always use hard tabs? If so, what property does that? I've tried the following to no avail:

```yaml
softTabs: false
hardTabs: true
tabType: 'hard'
```

I've even disabled the [tabs-to-spaces plugin](https://atom.io/packages/tabs-to-spaces) to ensure that it isn't overriding editor-settings' configuration, but it doesn't help.

Under the "Editor" configuration in Atom, "Atomic Soft Tabs" is enabled, "Soft Tabs" is disabled, "Tab Type" is set to "auto".

**Comment by asbjornu** [comment]
Seems like a restart of Atom made `tabType: 'hard'` (and nothing else) work. Is a restart required?

**Comment by nirix** [comment]
To use tabs the following should work, a restart shouldn't be required:

````
softTabs: false
````

I'll do some testing to make sure it still works, I've been using a few different editors lately and haven't had time to really test the latest Atom versions.

**Comment by nirix** [comment]
Did some testing with the latest version of Atom. The following config works without restarting Atom.

It forces Atom to use 4 spaces for indentation in PHP files, the `extensionConfig` forces tabs in PHP files with a `.phtml` file extension.

````cson
softTabs: true
tabLength: 4
extensionConfig:
  'phtml':
    softTabs: false
````

**Comment by asbjornu** [comment]
@nirix: That's weird. I had a `visual-studio-solution.cson` file with nothing but this in it:

```yaml
tabType: 'hard'
```

And it also worked. But I now have this:

```yaml
softTabs: false
```

And that works too. So 👍  and ¯\_(ツ)_/¯  I guess. 😄
