### ISSUE TITLE
Cannot get the package working

### ISSUE THREAD

**Issue by jberthet** [nirix/atom-editor-settings#7]
Hello,

I've installed the package and created a ".editor-settings" at the root of a project.

In that file, I've put :

`'tabLength': 10`

Anyway, when I open any file in the project and press the "tab" key, the indent length is 2, which is my editor default settings.

Tried to close anything and relaunch Atom without any success.

Thanks for any help on that issue.

**Comment by nirix** [comment]
Should be working now.

**Comment by jberthet** [comment]
The package still have no effect on my computer. Even after uninstall and reinstallation.

**Comment by jasperkennis** [comment]
I'm having the same issue. Just installed the latest version of the plugin; not seeing any effects.

**Comment by nirix** [comment]
Should be fixed in `1.0.0`.

**Comment by jasperkennis** [comment]
Genius, yes!

**Comment by ai-nikolai** [comment]
Cannot get it to work on per directory basis - installed, closed, reinstalled etc. 

What I have done:
1. Create `.editor-settings` under the directory I want the changes to happen
2. Content is:
```
tabLength: 2
softTabs: true
```
3. Tabs have length 4 (Editor default settings)
