### ISSUE TITLE
Object.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by jasperkennis** [nirix/atom-editor-settings#8]
Atom throws:

Requiring `$` from `atom` is no longer supported.
If you are using `space-pen`, please require `$` from `atom-space-pen-views`. Otherwise require `jquery` instead:
  `{$} = require 'atom-space-pen-views'`
  or
  `$ = require 'jquery'`
Add `"atom-space-pen-views": "^2.0.3"` to your package dependencies.
Or add `"jquery": "^2"` to your package dependencies.
```
Object.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app.asar/exports/atom.js:48:11)
Object.<anonymous> (/Users/jasperkennis/.atom/packages/editor-settings/lib/editor-settings.coffee:1:1)
Object.<anonymous> (/Users/jasperkennis/.atom/packages/editor-settings/lib/editor-settings.coffee:212:4)
Module._compile (module.js:452:26)
```

#7 might be related to this, I'm experiencing the same problems.

**Comment by nirix** [comment]
Not sure why I had that line in there, I never used it, went ahead and removed the jQuery require and it seems to have fixed it.
